title: 一般社団法人mononone
locale: "ja-JP"
name: mononome inc. 
email: q@mumyo.org
description: >- # this means to ignore newlines until "baseurl:"
 一般社団法人mononone (もののね) \\ 
 mononone inc., a nonprofit incorporated association, founded by members of mumyo; named by Ryuichi Sakamoto.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mononone.mumyo.org" 
###twitter_username: jekyllrb
##github_username: mumyollc 
youtube_username: "@mumyollc"
##twitter_username: "mumyollc"
x_username: "mumyollc"

timezone: Asia/Tokyo

# Build settings
theme: minima
plugins:
  - jekyll-feed

minima:
#  date_format: "%b %-d, %Y"
  date_format: "%Y年%m月%d日"

show_excerpts: false


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
